# nginx-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/azhn/nginx-django-proxy:v2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: static-data
          mountPath: /usr/share/nginx/html/static  # Mount path for Django static files in NGINX container
      volumes:
      - name: static-data
        persistentVolumeClaim:
          claimName: static-data-pvc  # Use the same PVC as Django application
---
# nginx-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx
