apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  DATABASE_ENGINE: ZGphbmdvLmRiLmJhY2tlbmRzLnBvc3RncmVzcWw=
  DATABASE_HOST: bWFhdGRiLXNlcnZlci5wb3N0Z3Jlcy5kYXRhYmFzZS5henVyZS5jb20=
  DATABASE_NAME: bWFhdA==
  DATABASE_USER: bWFhdA==
  DATABASE_PASSWORD: TUBhdF9wbEB0Zm9ybTEyMw==
  JWT_SECRET_KEY: SldUX1MzQ1IzVF9LM1k=
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLSUyZG1xbnFqOXYyZSY4eWsqdD0jYisyLT1pITQ1KzE1MypALWcwKj0mJTFvZDE2el5t

